import { newDoctor } from "src/types";

export const sampleDoctor: newDoctor[] = [
  {
    name: "Dr. Priya Patel",
    speciality: ["Dermatologist"],
    experience: 8,
    qualification: "MBBS, MD (Dermatology)",
    clinicLocation: "Skin Care Clinic - Mumbai",
    consult_fees: 600,
    Physical_fees: 500,
    mode: ["physical", "online"],
    image: "https://randomuser.me/api/portraits/women/23.jpg",
    about: [
      "Dr. Priya Patel is a leading dermatologist specializing in cosmetic dermatology and skin rejuvenation.",
      "She offers a wide range of treatments for acne, eczema, and other skin conditions.",
      "Dr. Patel is committed to providing personalized care to her patients.",
    ],
    isAvailable: false,
    languages: ["english"],
    faculty: "Other Clinics",
  },
  {
    name: "Dr. Rajesh Kumar",
    speciality: ["Orthopedic Surgeon"],
    experience: 12,
    qualification: "MBBS, MS (Orthopedics)",
    clinicLocation: "City Orthopedic Center - Chennai",
    consult_fees: 700,
    Physical_fees: 550,
    mode: ["physical", "online"],
    image: "https://randomuser.me/api/portraits/men/76.jpg",
    about: [
      "Dr. Rajesh Kumar is an experienced orthopedic surgeon specializing in joint replacement and sports injuries.",
      "He is dedicated to providing comprehensive orthopedic care to his patients.",
      "Dr. Kumar is actively involved in research and education in the field of orthopedics.",
    ],
    isAvailable: true,
    languages: ["tamil", "hindi"],
    faculty: "Government Hospital",
  },
  {
    name: "Dr. Anjali Singh",
    speciality: ["Gynecologist"],
    experience: 9,
    qualification: "MBBS, MD (Gynecology)",
    clinicLocation: "Women's Health Clinic - Kolkata",
    Physical_fees: 450,
    mode: ["physical"],
    image: "https://randomuser.me/api/portraits/women/45.jpg",
    about: [
      "Dr. Anjali Singh is a compassionate gynecologist providing comprehensive care for women's health issues.",
      "She specializes in reproductive health, prenatal care, and family planning.",
      "Dr. Singh is committed to empowering women to make informed decisions about their health.",
    ],
    isAvailable: true,
    languages: ["bengali"],
    faculty: "Private Practice",
  },
  {
    name: "Dr. Sanjay Gupta",
    speciality: ["Pediatrician"],
    experience: 11,
    qualification: "MBBS, MD (Pediatrics)",
    clinicLocation: "Children's Hospital - Bangalore",
    consult_fees: 620,
    mode: ["online"],
    image: "https://randomuser.me/api/portraits/men/22.jpg",
    about: [
      "Dr. Sanjay Gupta is a dedicated pediatrician providing comprehensive care for infants, children, and adolescents.",
      "He specializes in childhood illnesses, vaccinations, and developmental issues.",
      "Dr. Gupta is committed to creating a warm and welcoming environment for his young patients.",
    ],
    isAvailable: false,
    languages: ["kannada"],
    faculty: "Apollo Hospital",
  },
  {
    name: "Dr. Meera Reddy",
    speciality: ["Ophthalmologist"],
    experience: 7,
    qualification: "MBBS, MD (Ophthalmology)",
    clinicLocation: "Eye Care Center - Hyderabad",
    consult_fees: 580,
    Physical_fees: 460,
    mode: ["physical", "online"],
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    about: [
      "Dr. Meera Reddy is a skilled ophthalmologist specializing in the diagnosis and treatment of eye diseases.",
      "She offers comprehensive eye exams, cataract surgery, and glaucoma management.",
      "Dr. Reddy is dedicated to preserving and improving her patients' vision.",
    ],
    isAvailable: true,
    languages: ["telugu"],
    faculty: "Government Hospital",
  },
  {
    name: "Dr. Vikram Verma",
    speciality: ["Neurologist"],
    experience: 14,
    qualification: "MBBS, MD (Neurology), DM",
    clinicLocation: "Neuro Clinic - Mumbai",
    consult_fees: 900,
    Physical_fees: 700,
    mode: ["physical", "online"],
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    about: [
      "Dr. Vikram Verma is a leading neurologist with expertise in treating neurological disorders such as stroke, epilepsy, and Parkinson's disease.",
      "He utilizes advanced diagnostic techniques and therapies to provide the best possible care for his patients.",
      "Dr. Verma is actively involved in research and education in the field of neurology.",
    ],
    isAvailable: true,
    languages: ["hindi"],
    faculty: "Private Practice",
  },
  {
    name: "Dr. Neha Sharma",
    speciality: ["Cardiologist"],
    experience: 10,
    qualification: "MBBS, MD (Cardiology)",
    clinicLocation: "Heart Care Clinic - Delhi",
    consult_fees: 850,
    Physical_fees: 700,
    mode: ["physical", "online"],
    image: "https://randomuser.me/api/portraits/women/34.jpg",
    about: [
      "Dr. Neha Sharma is a highly skilled cardiologist specializing in the diagnosis and treatment of heart diseases.",
      "She offers comprehensive cardiac care, including preventive cardiology and interventional procedures.",
      "Dr. Sharma is dedicated to improving her patients' heart health and overall well-being.",
    ],
    isAvailable: false,
    languages: ["english", "hindi"],
    faculty: "Max Hospital",
  },
  {
    name: "Dr. Arjun Nair",
    speciality: ["Endocrinologist"],
    experience: 6,
    qualification: "MBBS, MD (Endocrinology)",
    clinicLocation: "Diabetes and Hormone Clinic - Chennai",
    consult_fees: 720,
    Physical_fees: 600,
    mode: ["physical", "online"],
    image: "https://randomuser.me/api/portraits/men/55.jpg",
    about: [
      "Dr. Arjun Nair is a dedicated endocrinologist specializing in diabetes management and hormonal disorders.",
      "He provides personalized care and treatment plans for patients with diabetes, thyroid disorders, and other endocrine issues.",
      "Dr. Nair is committed to empowering his patients to take control of their health.",
    ],
    isAvailable: true,
    languages: ["tamil", "english"],
    faculty: "Apollo Hospital",
  },
];
